# <font color='blue'>Data Science Academy - Machine Learning</font>

# <font color='blue'>Capítulo 12 - Processamento de Linguagem Natural</font>

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.7.6


Obs: Este é um material de bônus incluído neste curso. PyTorch é estudado em detalhes no curso <a href="https://www.datascienceacademy.com.br/course?courseid=deep-learning-frameworks">Deep Learning Frameworks</a> e aplicado em PLN no curso <a href="https://www.datascienceacademy.com.br/course?courseid=processamento-de-linguagem-natural-e-reconhecimento-de-voz">Processamento de Linguagem Natural</a>.

## Introdução ao Framework PyTorch

A computação em modelos de Deep Learning é feita com tensores, que são generalizações de uma matriz que pode ser indexada em mais de duas dimensões. O PyTorch é um framework que aplica operações matemáticas a tensores para então treinar modelos de Deep Learning.

https://pytorch.org/

**TorchScript**

O PyTorch TorchScript ajuda a criar modelos serializáveis e otimizáveis. Depois que treinamos esses modelos, eles também podem ser executados independentemente. Isso ajuda quando estamos no estágio de implantação do modelo de um projeto de Data Science.

Você pode treinar um modelo no PyTorch usando Python e depois exportá-lo via TorchScript para um ambiente de produção em que Python não esteja disponível. 

**Treinamento Distribuído**

O PyTorch também oferece suporte a treinamento distribuído que permite que pesquisadores e profissionais paralelizem seus cálculos. O treinamento distribuído possibilita o uso de várias GPUs para processar lotes maiores de dados de entrada. Isso, por sua vez, reduz o tempo de computação.

**Suporte para Python**

O PyTorch tem uma interação muito boa com o Python. De fato, a codificação no PyTorch é bastante semelhante ao que fazemos em Python. Portanto, se você se sentir confortável com o Python, vai adorar trabalhar com o PyTorch.

### O Que São Tensores?

![title](imagens/tensores.png)

In [2]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install torch==1.5.0

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
!pip install -q -U watermark

In [3]:
# Instala o PyTorch
!pip install -q -U torch torchvision

In [4]:
# Imports
import numpy 
import torch
import torchvision

In [5]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Data Science Academy" --iversions

torchvision 0.6.0
torch       1.5.0
numpy       1.18.4
Data Science Academy


### Criando e Manipulando Tensores

A razão pela qual usamos o Numpy em Machine Learning é que é muito mais rápido do que as listas Python na execução de operações de matriz. 

Por quê? Internamente, NumPy faz a maior parte do trabalho pesado em Linguagem C, que é muito mais veloz que Python. 

Mas, no caso de treinar redes neurais profundas (<a href="http://www.deeplearningbook.com.br/">Deep Learning</a>), os arrays NumPy levariam meses para treinar algumas das redes de ponta. É aqui que os tensores entram em cena. O PyTorch nos fornece uma estrutura de dados chamada Tensor, que é muito semelhante à matriz ND do NumPy. Mas, diferentemente do último, os tensores podem aproveitar os recursos de uma GPU para acelerar significativamente as operações com matrizes.

In [6]:
# Criando um tensor
x = torch.tensor([1., 2.])

In [7]:
# Visualiza o tensor
print(x)

tensor([1., 2.])


In [8]:
# Shape
print(x.shape)

torch.Size([2])


In [9]:
# Criando um tensor
t = torch.tensor([[1,1,1,1],
                  [2,2,2,2],
                  [3,3,3,3]], dtype = torch.float32)

Para determinar a forma desse tensor, examinamos primeiro as linhas (3) e depois as colunas (4). Portanto, esse tensor é 3 x 4 de classificação (rank) 2. 

Rank é uma palavra comumente usada e significa apenas o número de dimensões presentes no tensor.

No PyTorch, temos duas maneiras de obter a forma (shape):

In [10]:
t.size()

torch.Size([3, 4])

In [11]:
t.shape

torch.Size([3, 4])

No PyTorch, o tamanho e a forma de um tensor significam a mesma coisa.

Normalmente, depois de conhecermos a forma de um tensor, podemos deduzir algumas coisas. Primeiro, podemos deduzir o rank do tensor. O rank de um tensor é igual ao comprimento da forma do tensor.

In [12]:
len(t.shape)

2

In [13]:
len(x.shape)

1

Também podemos deduzir o número de elementos contidos no tensor. O número de elementos dentro de um tensor (12 no nosso caso do tensor t e 2 no tensor x) é igual ao produto dos valores dos componentes da forma.

In [14]:
torch.tensor(t.shape).prod()

tensor(12)

In [15]:
torch.tensor(x.shape).prod()

tensor(2)

In [16]:
# Retornando um elemento de um tensor
z = torch.tensor([[1., 2.],[5., 3.],[0., 4.]])

In [17]:
print(z)

tensor([[1., 2.],
        [5., 3.],
        [0., 4.]])


In [18]:
# Shape
print(z.shape)

torch.Size([3, 2])


In [19]:
# Retornamos a primeira linha (índice 0) e segunda coluna (índice 1)
# O retorno é no formato de tensor
print(z[0][1])

tensor(2.)


In [20]:
# Retornamos a primeira linha (índice 0) e segunda coluna (índice 1)
# O retorno é no formato de escalar (apenas o valor)
print(z[0][1].item())

2.0


Quando criamos tensores com valores randômicos, passamos apenas o número de dimensões.

In [21]:
input1 = torch.randn([1, 4, 4, 2])

In [22]:
input2 = torch.randn(1, 4, 4, 2)

In [23]:
input1.shape

torch.Size([1, 4, 4, 2])

In [24]:
input2.shape

torch.Size([1, 4, 4, 2])

In [25]:
len(input1.shape)

4

In [26]:
len(input2.shape)

4

In [27]:
input1

tensor([[[[-0.9482, -2.0921],
          [ 0.3113, -0.2121],
          [-0.1855, -1.5270],
          [-2.1619,  0.5348]],

         [[ 0.0283,  0.8341],
          [-0.2790, -1.8271],
          [-1.1628,  1.1019],
          [ 1.2481,  0.6488]],

         [[-0.1437,  0.3013],
          [-1.9909,  0.4203],
          [-0.0676,  0.4896],
          [ 1.7732,  0.1931]],

         [[ 1.0709, -1.0066],
          [-1.5297,  0.4276],
          [-0.4646, -0.1275],
          [ 0.4280, -0.8285]]]])

In [28]:
input2

tensor([[[[ 0.6759,  0.3791],
          [-1.9885, -1.3901],
          [ 0.1562, -0.2756],
          [-1.2489,  1.4699]],

         [[ 0.7904,  1.2076],
          [-0.3212,  0.8936],
          [ 0.0537,  0.4397],
          [-0.0280,  0.8703]],

         [[ 0.6236, -0.5518],
          [-0.4955, -1.3179],
          [-0.2664, -0.5521],
          [ 1.7409, -0.0457]],

         [[ 1.0288, -0.0135],
          [-2.0351,  0.5283],
          [-1.9646,  0.2570],
          [-2.1678,  1.1651]]]])

Considere tensores como o número de listas que uma dimensão contém. Por exemplo, um tensor (1, 4, 4, 2) terá:

1 lista contendo 4 elementos de 4 elementos de 2 elementos.

- A primeira dimensão pode conter 1 elemento.
- A segunda dimensão pode conter 4 elementos.
- A terceira dimensão pode conter 4 elementos.
- A quarta dimensão pode conter 2 elementos.

![title](imagens/tensor.jpg)

### Array NumPy x Tensor PyTorch

In [29]:
# Cria um array NumPy
a = numpy.array(1)

# Cria um tensor PyTorch
b = torch.tensor(1)

In [30]:
# Tipo
type(a)

numpy.ndarray

In [31]:
# Tipo
type(b)

torch.Tensor

In [32]:
# Print
print(a)
print(b)

1
tensor(1)


### Operações com Tensores

In [33]:
# Criamos 2 tensores
t1 = torch.tensor(12)
t2 = torch.tensor(4)
print(t1, t2)

tensor(12) tensor(4)


In [34]:
# Soma
print(t1 + t2)

tensor(16)


In [35]:
# Subtração
print(t1 - t2)

tensor(8)


In [36]:
# Multiplicação
print(t1 * t2)

tensor(48)


In [37]:
# Divisão
print(t1 // t2)

tensor(3)


### Operações com Matrizes

In [38]:
# Matriz (tensor rank 2) de números randômicos
t_rank2 = torch.randn(3,3)
t_rank2

tensor([[ 0.7061, -0.7973, -0.8862],
        [-0.8444,  0.3050, -0.6548],
        [-0.5375,  0.2029, -0.2691]])

In [39]:
# Tensor rank 3 de números randômicos
t_rank3 = torch.randn(3,3,3)
t_rank3

tensor([[[ 1.3711,  0.9683,  1.7280],
         [-0.5977, -1.2608,  1.8208],
         [-0.3305, -0.2292, -1.1338]],

        [[-0.6335,  0.2361, -0.5647],
         [-1.5194,  0.8917, -0.9990],
         [ 0.3578,  1.4174,  0.5577]],

        [[ 1.8785,  0.8831,  0.3485],
         [-0.4680,  0.0158, -0.2854],
         [-0.5237, -0.1388, -0.0783]]])

In [40]:
# Tensor rank 4 de números randômicos
t_rank4 = torch.randn(3,3,3,3)
t_rank4

tensor([[[[-3.6111e-01,  1.7164e+00, -7.9318e-01],
          [ 8.4382e-01,  1.4143e-01,  3.3228e-01],
          [ 1.6688e-01,  1.1503e+00,  3.0483e-01]],

         [[ 7.9292e-01,  1.5918e+00,  1.1394e+00],
          [ 1.4560e-01,  8.0305e-01,  5.7699e-01],
          [ 5.6801e-01, -1.0741e+00,  9.4300e-01]],

         [[-1.3003e-01,  3.9009e-01,  4.5485e-01],
          [-8.2032e-01, -1.2559e+00, -5.5603e-01],
          [ 1.3153e+00,  3.4276e-01,  1.8879e-01]]],


        [[[ 4.5932e-01, -2.6491e-01, -1.2201e+00],
          [-3.5190e-01, -4.0191e-01, -5.3090e-01],
          [-1.8362e+00, -9.7552e-01,  7.1177e-01]],

         [[ 1.0260e+00, -3.6225e-01, -4.9959e-01],
          [ 3.8540e-01,  2.4449e-01,  7.9880e-04],
          [-2.7408e-01, -1.9710e-01,  1.2974e+00]],

         [[-9.3920e-01,  1.7660e+00, -7.3842e-01],
          [-7.7712e-01, -5.1067e-01, -3.6833e-01],
          [ 8.0443e-01,  8.5275e-01,  1.7015e+00]]],


        [[[ 2.2601e-01, -1.0045e+00,  3.7911e-01],
          [-1.1

In [41]:
# Multiplicação entre 2 tensores
A = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = torch.tensor([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

In [42]:
A.shape

torch.Size([3, 3])

In [43]:
B.shape

torch.Size([3, 3])

In [44]:
len(A.shape)

2

In [45]:
len(B.shape)

2

In [46]:
A

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [47]:
B

tensor([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]])

In [48]:
resultado1 = A * B

In [49]:
# Resultado
print(resultado1)

tensor([[ 9, 16, 21],
        [24, 25, 24],
        [21, 16,  9]])


In [50]:
resultado2 = torch.matmul(A, B)

In [51]:
# Resultado
print(resultado2)

tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])


In [52]:
resultado3 = torch.sum(A * B)

In [53]:
# Resultado
print(resultado3)

tensor(165)


![title](imagens/mat-mul.gif)

Para multiplicação de matrizes, fazemos assim em PyTorch:

In [54]:
AB1 = A.mm(B)
# ou
AB2 = torch.mm(A, B)
# ou
AB3 = torch.matmul(A, B)
# Ou assim (Python 3.5+)
AB4 = A @ B 

In [55]:
print(AB1)
print(AB2)
print(AB3)
print(AB4)

tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])
tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])
tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])
tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])


In [56]:
# Multiplicação de matrizes
A @ B

tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])

Essa notação realiza multiplicação element-wise:

In [57]:
# Operação element-wise
A * B

tensor([[ 9, 16, 21],
        [24, 25, 24],
        [21, 16,  9]])

In [58]:
# Usando seed para iniciar 2 tensores com valores randômicos
torch.manual_seed(42)
a = torch.randn(3,3)
b = torch.randn(3,3)

In [59]:
# Adição de matrizes
print(torch.add(a, b))

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]])


In [60]:
# Subtração de matrizes
print(torch.sub(a, b))

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]])


In [61]:
# Multiplicação de matrizes
print(torch.mm(a, b))

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])


In [62]:
# Divisão de matrizes
print(torch.div(a, b))

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])


In [63]:
# Matriz Original
print(a, '\n')

# Matriz Transposta
torch.t(a)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]]) 



tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])

# Fim